import { useState, useMemo } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { deleteInvoice } from '../services/invoiceService';
import type { Invoice } from '../types';
import { toast } from 'react-hot-toast';
import { downloadCsv } from '../lib/csv';

const EXCEL_HEADERS = ['Invoice No', 'Customer', 'Date', 'Amount', 'Status', 'IRN No'];

export default function Invoices() {
  const queryClient = useQueryClient();
  const [search, setSearch] = useState('');

  const { data: invoices = [], isLoading } = useQuery({
    queryKey: ['invoices'],
    queryFn: async () => {
      const { data } = await supabase
        .from('invoices')
        .select('*')
        .order('created_at', { ascending: false });
      
      return (data ?? []).map(inv => ({
        ...inv,
        invoiceNumber: inv.invoice_no,
        customerName: inv.customer_name || 'N/A',
        grandTotal: inv.grand_total || 0,
      }));
    },
  });

  const filteredInvoices = useMemo(() => {
    return invoices.filter(inv => 
      inv.invoiceNumber.toLowerCase().includes(search.toLowerCase()) ||
      inv.customerName.toLowerCase().includes(search.toLowerCase())
    );
  }, [invoices, search]);

  const handleDelete = async (id: string) => {
    if (!confirm('PERMANENT ACTION: Are you sure you want to delete this invoice? This will revert customer balance.')) return;
    try {
      await deleteInvoice(id);
      toast.success('Invoice deleted successfully');
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
    } catch (err: any) {
      toast.error(err.message || 'Failed to delete invoice');
    }
  };

  const handleExportExcel = () => {
    const data = filteredInvoices.map(inv => ({
      'Invoice No': inv.invoiceNumber,
      'Customer': inv.customerName,
      'Date': inv.date,
      'Amount': inv.grandTotal,
      'Status': inv.status,
      'IRN No': inv.irnNo || 'N/A'
    }));
    downloadCsv(EXCEL_HEADERS, data, `Sales_Register_${new Date().toISOString().slice(0, 10)}.csv`);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <h2 className="text-2xl font-black text-slate-900 dark:text-slate-100 uppercase tracking-tight">Sales Register</h2>
          <p className="text-sm text-slate-500 font-medium">Manage and track all GST-compliant invoices generated by the system.</p>
        </div>
        <div className="flex gap-2">
          <button 
            onClick={handleExportExcel}
            className="rounded-3xl border border-slate-200 bg-white px-6 py-3 text-sm font-bold text-slate-700 transition hover:bg-slate-50 flex items-center gap-2 shadow-sm"
          >
            <span>📊</span> Export Excel
          </button>
          <Link
            to="/sales/invoices/new"
            className="inline-flex items-center gap-2 justify-center rounded-3xl bg-slate-900 px-6 py-3 text-sm font-bold text-white transition hover:bg-slate-800 shadow-lg"
          >
            <span>➕</span> Generate New
          </Link>
        </div>
      </div>

      <div className="glass-card rounded-3xl border border-slate-200 p-6 shadow-sm dark:border-slate-800">
        <div className="mb-6 flex flex-col gap-4 md:flex-row md:items-center">
          <div className="relative flex-1 max-w-md">
            <span>🔍</span>
            <input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by invoice # or buyer name..."
              className="w-full rounded-2xl border border-slate-200 bg-slate-50 pl-11 pr-4 py-2.5 text-sm outline-none transition focus:ring-2 focus:ring-slate-900/10 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100"
            />
          </div>
          <div className="flex items-center gap-2 text-xs font-bold text-slate-400 uppercase tracking-widest px-2">
            <span>📁</span> Filter: <span className="text-slate-900 dark:text-slate-100 underline decoration-indigo-500 underline-offset-4 cursor-pointer">All Transactions</span>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="min-w-full text-left text-sm text-slate-700 dark:text-slate-300">
            <thead>
              <tr className="text-[10px] uppercase tracking-[0.2em] text-slate-400 font-black border-b border-slate-100 dark:border-slate-800">
                <th className="px-4 py-4">Invoice Number</th>
                <th className="px-4 py-4">Buyer / Customer</th>
                <th className="px-4 py-4 text-center">Billing Date</th>
                <th className="px-4 py-4 text-right">Grand Total</th>
                <th className="px-4 py-4 text-center">Status</th>
                <th className="px-4 py-4 text-center">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50 dark:divide-slate-900">
              {isLoading ? (
                <tr>
                  <td colSpan={6} className="px-4 py-12 text-center">
                    <div className="flex flex-col items-center gap-3">
                      <span>⌛</span>
                      <p className="text-sm font-bold text-slate-400 uppercase tracking-widest">Fetching Sales Records...</p>
                    </div>
                  </td>
                </tr>
              ) : filteredInvoices.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-4 py-12 text-center">
                    <p className="text-sm font-bold text-slate-400 uppercase tracking-widest italic">No matching invoices found in database.</p>
                  </td>
                </tr>
              ) : (
                filteredInvoices.map((invoice) => (
                  <tr key={invoice.id} className="hover:bg-slate-50/50 dark:hover:bg-slate-900/30 transition-colors group">
                    <td className="px-4 py-4">
                      <Link 
                        to={`/sales/invoices/${invoice.id}`}
                        className="font-black text-slate-900 dark:text-slate-100 hover:text-indigo-600 transition-colors cursor-pointer"
                      >
                        {invoice.invoiceNumber}
                      </Link>
                      {invoice.irnNo && <div className="text-[9px] font-bold text-slate-400 truncate w-32">IRN: {invoice.irnNo}</div>}
                    </td>
                    <td className="px-4 py-4">
                      <div className="font-bold text-slate-700 dark:text-slate-300">{invoice.customerName}</div>
                    </td>
                    <td className="px-4 py-4 text-center">
                      <div className="font-mono text-xs text-slate-500">{invoice.date.split('T')[0]}</div>
                    </td>
                    <td className="px-4 py-4 text-right">
                      <div className="font-black text-slate-900 dark:text-slate-100">₹{invoice.grandTotal.toFixed(2)}</div>
                    </td>
                    <td className="px-4 py-4 text-center">
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider ${
                        invoice.status === 'Paid' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400' :
                        invoice.status === 'Draft' ? 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-400' :
                        'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400'
                      }`}>
                        {invoice.status}
                      </span>
                    </td>
                    <td className="px-4 py-4">
                      <div className="flex justify-center gap-1">
                        <Link
                          to={`/sales/invoices/${invoice.id}`}
                          title="View Details"
                          className="p-2 rounded-xl text-slate-400 hover:bg-slate-100 hover:text-slate-900 dark:hover:bg-slate-800 transition-all"
                        >
                          <span>👁️</span>
                        </Link>
                        <Link
                          to={`/sales/invoices/edit/${invoice.id}`}
                          title="Edit Invoice"
                          className="p-2 rounded-xl text-slate-400 hover:bg-amber-50 hover:text-amber-600 dark:hover:bg-amber-900/20 transition-all"
                        >
                          <span>✏️</span>
                        </Link>
                        <button
                          onClick={() => handleDelete(invoice.id)}
                          title="Delete Invoice"
                          className="p-2 rounded-xl text-slate-400 hover:bg-rose-50 hover:text-rose-600 dark:hover:bg-rose-900/20 transition-all"
                        >
                          <span>🗑️</span>
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
